# Generated by Django 2.1.2 on 2019-01-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('adminmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='easy.AdminModel')),
                ('article_id', models.IntegerField(verbose_name='文章编号')),
                ('edit_time', models.DateTimeField(verbose_name='修改时间')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('editor', models.CharField(max_length=30, verbose_name='编辑')),
                ('content', models.TextField(max_length=100000, verbose_name='内容')),
                ('creator_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='创建者ID')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
            bases=('easy.adminmodel',),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('article_id', 'edit_time')},
        ),
    ]
